### ISSUE TITLE
[Enhancement] - docker-compose example

### ISSUE THREAD

**Issue by Th3irdEye** [SnickCH/InsurgencySandstormDedicatedServer#6]
The readme said if someone had a working docker-compose config to drop it here as an example so here is my working config edited to remove personal information.

```
  sandstorm:
    image: snickch/insurgencysandstormdedicatedserver:latest
    container_name: sandstorm
    restart: always
    ports:
      - 27103:27103/tcp
      - 27103:27103/udp
      - 27133:27133/tcp
      - 27133:27133/udp
      - 29093:29093/tcp
      - 29093:29093/udp
    volumes:
      - /path/to/config/data/Game.ini:/home/steam/steamcmd/sandstorm/Insurgency/Saved/Config/LinuxServer/Game.ini:ro
      - /path/to/config/data/GameUserSettings.ini:/home/steam/steamcmd/sandstorm/Insurgency/Saved/Config/LinuxServer/GameUserSettings.ini:ro
      - /path/to/config/data/Admins.txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server/Admins.txt:ro
      - /path/to/config/data/Mods.txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server/Mods.txt:ro
      - /path/to/config/data/MapCycle.txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server/MapCycle.txt:ro
      - /path/to/mod/data/Mods/:/home/steam/steamcmd/sandstorm/Insurgency/Mods
    entrypoint: ./InsurgencyServer-Linux-Shipping
    command:
      -Port=27103
      -QueryPort=27133
      -Mods
      -Rcon
      -Mutators="Medic,ImprovedAI,ScaleSurvival,Vampirism,sBomber,PrintCount,JoinLeaveMessage,MoreAmmo"
      -ModDownloadTravelTo="Gap?Scenario=Scenario_Gap_Survival?lighting=day"
      -GSLTToken=YOURGSLTTOKEN
      -GameStatsToken=YOURGAMESTATSTOKEN
```

You should just have to drop your GSLT and GameStats tokens in, set up the paths the way you want, and make sure you create the .txt and .ini files on your host before creating the container so docker-compose doesn't create directories instead and it should all be working. You can also of course adjust which mutators you want active and what scenario to start the server on as well.

Also, kudos to being the only one of the 4 or so different sandstorm containers I tried that was documented well enough that I was able to set up a working compose configuration. Thanks for the hard work!
